# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a71a753ea42805e77a554295224f3f1df16af04043d1a0ebfd735f1c3edd9800f9ecbe68795f42837b776969f5244f73b3634cd9e1e0052a4607d26fa414d80

test:
  secret_key_base: 76bca9967caf3b5df3119f4ca8a21b2a015f68452959930579ea83e7814a2c84c6928594d2dd0f20bdd464231ada01320632e2308b21f59e16010c9f56263c8f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
